### ISSUE TITLE
Liquid types question 

### ISSUE THREAD

**Issue by bartaz61** [BlueMoonVineyard/BreweryNG#3]
I saw that you added an option to use liquid types needed to make a specific brew, but I don't know how to add it in a config.

**Comment by sowelipililimute** [comment]
You use the `liquid` key under a recipe to specify the liquid type:
```yaml
recipes:
  someRecipe:
    name: Bad Recipe/Recipe/Good Recipe
    liquid: water
```
It can be one of `water`, `lava`, or `snow`.
